.\" Manpage of urldiff/v0.1.1.0
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v1.8.1
.\" generated with Ronn/v0.7.3
.
.TH "URLDIFF" "1" "2014-07-26" "0.1.1.0" "User Manual"
.
.SH "NAME"
\fBurldiff\fR \- notify and watch changes on websites
.
.SH "SYNOPSIS"
urldiff (\-h|\-v) (\-nv|\-nv|\-q) [\-m]
.
.SH "REQUIREMENT"
awk, bash, cmp, cp, diff, find, mailx, md5sum, mkdir, mv, ping, rename, rm, sed, tput, w3m, wget, xargs
.
.SH "OPTIONAL"
dwdiff, wdiff
.
.SH "DESCRIPTION"
\fBurldiff\fR is a simple bash shell script to notify and watch changes on websites, that do not provide Atom or RSS\-Feed\. After reading an url list, downloading and comparision of "local" and "online" a little status report will be generated\. The status is constructed like this:
.
.P
FAIL 2014\-02\-12_15:43 URL: http://www\.fcstpauli\.hsv/ unattainable
.br
FAIL 2014\-02\-12_15:43 URL: httttp://www\.fcstpauli\.com/ does not match
.br
NEW 2014\-02\-12_15:43 URL: http://www\.naturkundemuseum\-berlin\.de/institution/jobs\-und\-karriere/
.br
    file:///home/user/\.urldiff/diff/53e4a875ad5c7ea306cccf991f2768f7_diff\.txt
.br
    file:///home/user/\.urldiff/cache/53e4a875ad5c7ea306cccf991f2768f7\.html
.br
    file:///home/user/\.urldiff/cache/53e4a875ad5c7ea306cccf991f2768f7\.txt
.br
OLD 2014\-02\-12_15:43 URL: http://www\.orgmode\.org/worg/org\-contrib/index\.html
.
.P
\fBurldiff\fR is an adaption of the activity\-monitor\. See \fB<https://github\.com/cmichi/activity\-monitor>\fR for details\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-help\fR
Display a short help\.
.
.TP
\fB\-m\fR, \fB\-mail\fR [\fIMAILTO\fR\.\.\.]
Send Report via mail to \fIMAILTO\fR\. If \fIMAILTO\fR is not specified, the configuration variable \fBmailto\fR will be used\.
.
.TP
\fB\-nv\fR, \fB\-no\-verbose\fR
Turn off verbose output without being completely quiet\.
.
.TP
\fB\-q\fR, \fB\-quiet\fR
Turn off output\.
.
.TP
\fB\-vb\fR, \fB\-verbose\fR
Turn on verbose output\. By default, this option is used\.
.
.TP
\fB\-v\fR, \fB\-version\fR
Print current version of \fBurldiff\fR\.
.
.SH "ARGUMENTS"
.
.TP
\fIMAILTO\fR
Something like: user@example\.org
.
.SH "EXAMPLES"
.
.TP
To print Report:
urldiff
.br
urldiff \-nv
.
.TP
To only mail the Report:
urldiff \-q \-m
.br
urldiff \-q \-m user1@example\.foo user2@example\.foo
.
.TP
To do both:
urldiff \-vb \-m
.
.SH "RETURN VALUES"
.
.TP
79
ERROR We are probably offline\.
.
.TP
80
ERROR No url list to look for\.
.
.SH "NOTES"
.
.IP "\(bu" 4
You can write all commands and options without masking \fB\-\fR\. So, instead of \fB\-help\fR you may use \fBhelp\fR\.
.
.IP "\(bu" 4
Urls in the url list need to be seperated by newline.
.
.IP "\(bu" 4
To check the connection status, \fB<google\.com>\fR will be pinged\. If you do not like that, modify it please\.
.
.IP "" 0
.
.SH "CONFIGURATION"
.
.TP
Set following variables in the second section of the script:
\fBurldiffdir=DIR\fR (needed)
.br
\fBurllist=FILE\fR (needed)
.br
\fBmailto=<MAILTO>\fR (optional)
.
.TP
Configure your favourite diff\-programm in the function called \fB__urldiff_diff()\fR\.

.
.SH "BUGS & REQUESTS"
Report it on \fB<https://github\.com/D630/urldiff>\fR
.
.SH "TODO"
.
.IP "\(bu" 4
Revise mechanism to get html\-body\.
.
.IP "" 0
.
.SH "LICENSE"
See file \fBLICENCE\fR, which comes along with this software\.
.
.SH "CHRONOLOGY"
First version (\fB0\.1\.0\.0\fR) was finished on 12\. February 2014\.
.
.SH "SEE ALSO"
\fBawk\fR(1), \fBbash\fR(1), \fBcmp\fR(1), \fBcp\fR(1), \fBdiff(1)\fR, \fBdwdiff\fR(1), \fBfind\fR(1), \fBmailx\fR(1), \fBmd5sum\fR(1), \fBmkdir\fR(1), \fBmv\fR(1), \fBping\fR(1), \fBrename\fR(1), \fBrm\fR(1), \fBsed\fR(1), \fBtput\fR(1), \fBw3m\fR(1), \fBwdiff\fR(1), \fBwget\fR(1), \fBxargs\fR(1)
